[{"ContainerToolsException.Message":"Error response from daemon: conflict: unable to remove repository reference \"productmicroservice:dev\" (must force) - container d20984e60e95 is using its referenced image 32131f5be9f8","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__16.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 289\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<DownAsync>d__9.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 122\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__34.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:line 444\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.ComposeDownContainers.<ExecuteCoreAsync>d__4.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\ComposeDownContainers.cs:line 16\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:line 84","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker-compose","ContainerToolsException.CommandLine.TelemetrySafeArguments":"","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":" Container ProductMicroservice  Stopping\r\n Container ProductMicroservice  Stopping\r\n Container ProductMicroservice  Stopped\r\n Container ProductMicroservice  Removing\r\n Container ProductMicroservice  Removed\r\n Image productmicroservice:dev  Removing\r\n Network dockercompose849409491404894164_default  Removing\r\n Network dockercompose849409491404894164_default  Removed\r\nError response from daemon: conflict: unable to remove repository reference \"productmicroservice:dev\" (must force) - container d20984e60e95 is using its referenced image 32131f5be9f8"},{"ContainerToolsException.Message":"Visual Studio Container Tools requires Docker to be running before building, debugging or running a containerized project.  For more info, please see: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Ddockercompose849409491404894164%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified.\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__16.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 289\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<DownAsync>d__9.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 111\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__34.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:line 444\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.ComposeDownContainers.<ExecuteCoreAsync>d__4.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\ComposeDownContainers.cs:line 16\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:line 84\r\nError code: DT1001\r\nSeverity: Error\r\nCommand line: docker-compose  -f \"C:\\Users\\arnol\\source\\repos\\ProductMicroservice\\docker-compose.yml\" -f \"C:\\Users\\arnol\\source\\repos\\ProductMicroservice\\docker-compose.override.yml\" -f \"C:\\Users\\arnol\\source\\repos\\ProductMicroservice\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose849409491404894164 --ansi never kill\r\nCommand exit code: 1\r\nCommand output: \r\nCommand error: error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Ddockercompose849409491404894164%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified.\r\n"}]